# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "847677867ab314566a73cbe017fbcac8"
name = "notyys"
handle = "notyys"
application_url = "https://austria-dom-pubs-agricultural.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_inventory"

[auth]
redirect_urls = ["https://austria-dom-pubs-agricultural.trycloudflare.com/auth/callback", "https://austria-dom-pubs-agricultural.trycloudflare.com/auth/shopify/callback", "https://austria-dom-pubs-agricultural.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "/apps/notyys"
subpath = "notyys"
prefix = "apps"

[pos]
embedded = false
